version: '2.1'
volumes:
  proxy: {}
  certs: {}
  db: {}
  duplicati: {}
  resin-data: {}
services:
  proxy:
    build:
      context: proxy
    network_mode: host
    volumes:
      - 'proxy:/data'
      - 'certs:/etc/letsencrypt'
    depends_on:
      - db
  db:
    build:
      context: mariadb
    volumes:
      - 'db:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: npm
    ports:
      - '3306:3306'
  sqldump:
    build:
      context: mariadb
    command: /sqldump.sh
    environment:
      MYSQL_DATABASE: npm
    volumes:
      - 'db:/var/lib/mysql'
    depends_on:
      - db
  duplicati:
    image: 'linuxserver/duplicati:arm32v7-latest'
    environment:
      PUID: '0'
      PGID: '0'
      CLI_ARGS: '--webservice-interface=any'
    ports:
      - '8200:8200/tcp'
    volumes:
      - 'duplicati:/config'
      - 'proxy:/source/proxy'
      - 'certs:/source/certs'
      - 'db:/source/db'
  ha:
    build:
      context: ./ha
    ports:
      - '8123:8123'
    volumes:
      - 'resin-data:/data'
